birdlist = {"CAPERCAILLIE": 1, 
         "BLACK GROUSE": 2, 
         "PTARMIGAN": 3, 
         "RED GROUSE": 4, 
         "RED-LEGGED PARTRIDGE": 5, 
         "GREY PARTRIDGE": 6, 
         "QUAIL": 7, 
         "PHEASANT": 8, 
         "GOLDEN PHEASANT": 9, 
         "LADY AMHERST'S PHEASANT": 10, 
         "BRENT GOOSE": 11, 
         "RED-BREASTED GOOSE": 12, 
         "CANADA GOOSE": 13, 
         "BARNACLE GOOSE": 14, 
         "CACKLING GOOSE": 15, 
         "SNOW GOOSE": 16, 
         "GREYLAG GOOSE": 17, 
         "TAIGA BEAN GOOSE": 18, 
         "PINK-FOOTED GOOSE": 19, 
         "TUNDRA BEAN GOOSE": 20, 
         "WHITE-FRONTED GOOSE": 21, 
         "LESSER WHITE-FRONTED GOOSE": 22, 
         "MUTE SWAN": 23, 
         "BEWICK'S SWAN": 24, 
         "WHOOPER SWAN": 25, 
         "EGYPTIAN GOOSE": 26, 
         "SHELDUCK": 27, 
         "RUDDY SHELDUCK": 28, 
         "MANDARIN DUCK": 29, 
         "BAIKAL TEAL": 30, 
         "GARGANEY": 31, 
         "BLUE-WINGED TEAL": 32, 
         "SHOVELER": 33, 
         "GADWALL": 34, 
         "FALCATED DUCK": 35, 
         "WIGEON": 36, 
         "AMERICAN WIGEON": 37, 
         "MALLARD": 38, 
         "BLACK DUCK": 39, 
         "PINTAIL": 40, 
         "TEAL": 41, 
         "GREEN-WINGED TEAL": 42, 
         "RED-CRESTED POCHARD": 43, 
         "CANVASBACK": 44, 
         "REDHEAD": 45, 
         "POCHARD": 46, 
         "FERRUGINOUS DUCK": 47, 
         "RING-NECKED DUCK": 48, 
         "TUFTED DUCK": 49, 
         "SCAUP": 50, 
         "LESSER SCAUP": 51, 
         "STELLER'S EIDER": 52, 
         "KING EIDER": 53, 
         "EIDER": 54, 
         "HARLEQUIN DUCK": 55, 
         "SURF SCOTER": 56, 
         "VELVET SCOTER": 57, 
         "WHITE-WINGED SCOTER": 58, 
         "COMMON SCOTER": 59, 
         "BLACK SCOTER": 60, 
         "LONG-TAILED DUCK": 61, 
         "BUFFLEHEAD": 62, 
         "GOLDENEYE": 63, 
         "BARROW'S GOLDENEYE": 64, 
         "SMEW": 65, 
         "HOODED MERGANSER": 66, 
         "GOOSANDER": 67, 
         "RED-BREASTED MERGANSER": 68, 
         "RUDDY DUCK": 69, 
         "COMMON NIGHTHAWK": 70, 
         "RED-NECKED NIGHTJAR": 71, 
         "NIGHTJAR": 72, 
         "EGYPTIAN NIGHTJAR": 73, 
         "WHITE-THROATED NEEDLETAIL": 74, 
         "CHIMNEY SWIFT": 75, 
         "ALPINE SWIFT": 76, 
         "SWIFT": 77, 
         "PALLID SWIFT": 78, 
         "PACIFIC SWIFT": 79, 
         "LITTLE SWIFT": 80, 
         "WHITE-RUMPED SWIFT": 81, 
         "GREAT BUSTARD": 82, 
         "MACQUEEN'S BUSTARD": 83, 
         "LITTLE BUSTARD": 84, 
         "GREAT SPOTTED CUCKOO": 85, 
         "YELLOW-BILLED CUCKOO": 86, 
         "BLACK-BILLED CUCKOO": 87, 
         "CUCKOO": 88, 
         "PALLAS'S SANDGROUSE": 89, 
         "ROCK DOVE": 90, 
         "STOCK DOVE": 91, 
         "WOODPIGEON": 92, 
         "TURTLE DOVE": 93, 
         "ORIENTAL TURTLE DOVE": 94, 
         "COLLARED DOVE": 95, 
         "MOURNING DOVE": 96, 
         "WATER RAIL": 97, 
         "CORNCRAKE": 98, 
         "LITTLE CRAKE": 99, 
         "BAILLON'S CRAKE": 100, 
         "SPOTTED CRAKE": 101, 
         "SORA RAIL": 102, 
         "WESTERN SWAMPHEN": 103, 
         "ALLEN'S GALLINULE": 104, 
         "AMERICAN PURPLE GALLINULE": 105, 
         "MOORHEN": 106, 
         "COOT": 107, 
         "AMERICAN COOT": 108, 
         "SANDHILL CRANE": 109, 
         "CRANE": 110, 
         "LITTLE GREBE": 111, 
         "PIED-BILLED GREBE": 112, 
         "RED-NECKED GREBE": 113, 
         "GREAT CRESTED GREBE": 114, 
         "SLAVONIAN GREBE": 115, 
         "BLACK-NECKED GREBE": 116, 
         "STONE-CURLEW": 117, 
         "OYSTERCATCHER": 118, 
         "BLACK-WINGED STILT": 119, 
         "AVOCET": 120, 
         "LAPWING": 121, 
         "SOCIABLE PLOVER": 122, 
         "WHITE-TAILED PLOVER": 123, 
         "GOLDEN PLOVER": 124, 
         "PACIFIC GOLDEN PLOVER": 125, 
         "AMERICAN GOLDEN PLOVER": 126, 
         "GREY PLOVER": 127, 
         "RINGED PLOVER": 128, 
         "SEMIPALMATED PLOVER": 129, 
         "LITTLE RINGED PLOVER": 130, 
         "KILLDEER": 131, 
         "KENTISH PLOVER": 132, 
         "LESSER SAND PLOVER": 133, 
         "GREATER SAND PLOVER": 134, 
         "CASPIAN PLOVER": 135, 
         "DOTTEREL": 136, 
         "UPLAND SANDPIPER": 137, 
         "WHIMBREL": 138, 
         "HUDSONIAN WHIMBREL": 139, 
         "LITTLE WHIMBREL": 140, 
         "ESKIMO CURLEW": 141, 
         "CURLEW": 142, 
         "BAR-TAILED GODWIT": 143, 
         "BLACK-TAILED GODWIT": 144, 
         "HUDSONIAN GODWIT": 145, 
         "TURNSTONE": 146, 
         "GREAT KNOT": 147, 
         "KNOT": 148, 
         "RUFF": 149, 
         "BROAD-BILLED SANDPIPER": 150, 
         "SHARP-TAILED SANDPIPER": 151, 
         "STILT SANDPIPER": 152, 
         "CURLEW SANDPIPER": 153, 
         "TEMMINCK'S STINT": 154, 
         "LONG-TOED STINT": 155, 
         "RED-NECKED STINT": 156, 
         "SANDERLING": 157, 
         "DUNLIN": 158, 
         "PURPLE SANDPIPER": 159, 
         "BAIRD'S SANDPIPER": 160, 
         "LITTLE STINT": 161, 
         "LEAST SANDPIPER": 162, 
         "WHITE-RUMPED SANDPIPER": 163, 
         "BUFF-BREASTED SANDPIPER": 164, 
         "PECTORAL SANDPIPER": 165, 
         "SEMIPALMATED SANDPIPER": 166, 
         "WESTERN SANDPIPER": 167, 
         "LONG-BILLED DOWITCHER": 168, 
         "SHORT-BILLED DOWITCHER": 169, 
         "WOODCOCK": 170, 
         "JACK SNIPE": 171, 
         "GREAT SNIPE": 172, 
         "SNIPE": 173, 
         "WILSON'S SNIPE": 174, 
         "TEREK SANDPIPER": 175, 
         "WILSON'S PHALAROPE": 176, 
         "RED-NECKED PHALAROPE": 177, 
         "GREY PHALAROPE": 178, 
         "COMMON SANDPIPER": 179, 
         "SPOTTED SANDPIPER": 180, 
         "GREEN SANDPIPER": 181, 
         "SOLITARY SANDPIPER": 182, 
         "GREY-TAILED TATTLER": 183, 
         "LESSER YELLOWLEGS": 184, 
         "REDSHANK": 185, 
         "MARSH SANDPIPER": 186, 
         "WOOD SANDPIPER": 187, 
         "SPOTTED REDSHANK": 188, 
         "GREENSHANK": 189, 
         "GREATER YELLOWLEGS": 190, 
         "CREAM-COLOURED COURSER": 191, 
         "COLLARED PRATINCOLE": 192, 
         "ORIENTAL PRATINCOLE": 193, 
         "BLACK-WINGED PRATINCOLE": 194, 
         "KITTIWAKE": 195, 
         "IVORY GULL": 196, 
         "SABINE'S GULL": 197, 
         "SLENDER-BILLED GULL": 198, 
         "BONAPARTE'S GULL": 199, 
         "BLACK-HEADED GULL": 200, 
         "LITTLE GULL": 201, 
         "ROSS'S GULL": 202, 
         "LAUGHING GULL": 203, 
         "FRANKLIN'S GULL": 204, 
         "AUDOUIN'S GULL": 205, 
         "MEDITERRANEAN GULL": 206, 
         "GREAT BLACK-HEADED GULL": 207, 
         "COMMON GULL": 208, 
         "RING-BILLED GULL": 209, 
         "GREAT BLACK-BACKED GULL": 210, 
         "GLAUCOUS-WINGED GULL": 211, 
         "GLAUCOUS GULL": 212, 
         "ICELAND GULL": 213, 
         "HERRING GULL": 214, 
         "AMERICAN HERRING GULL": 215, 
         "CASPIAN GULL": 216, 
         "YELLOW-LEGGED GULL": 217, 
         "SLATY-BACKED GULL": 218, 
         "LESSER BLACK-BACKED GULL": 219, 
         "GULL-BILLED TERN": 220, 
         "CASPIAN TERN": 221, 
         "ROYAL TERN": 222, 
         "LESSER CRESTED TERN": 223, 
         "SANDWICH TERN": 224, 
         "CABOT'S TERN": 225, 
         "ELEGANT TERN": 226, 
         "LITTLE TERN": 227, 
         "LEAST TERN": 228, 
         "ALEUTIAN TERN": 229, 
         "BRIDLED TERN": 230, 
         "SOOTY TERN": 231, 
         "ROSEATE TERN": 232, 
         "COMMON TERN": 233, 
         "ARCTIC TERN": 234, 
         "FORSTER'S TERN": 235, 
         "WHISKERED TERN": 236, 
         "WHITE-WINGED BLACK TERN": 237, 
         "BLACK TERN": 238, 
         "GREAT SKUA": 239, 
         "POMARINE SKUA": 240, 
         "ARCTIC SKUA": 241, 
         "LONG-TAILED SKUA": 242, 
         "LITTLE AUK": 243, 
         "BRÜNNICH'S GUILLEMOT": 244, 
         "COMMON GUILLEMOT": 245, 
         "RAZORBILL": 246, 
         "GREAT AUK": 247, 
         "BLACK GUILLEMOT": 248, 
         "LONG-BILLED MURRELET": 249, 
         "ANCIENT MURRELET": 250, 
         "PUFFIN": 251, 
         "TUFTED PUFFIN": 252, 
         "RED-BILLED TROPICBIRD": 253, 
         "RED-THROATED DIVER": 254, 
         "BLACK-THROATED DIVER": 255, 
         "PACIFIC DIVER": 256, 
         "GREAT NORTHERN DIVER": 257, 
         "WHITE-BILLED DIVER": 258, 
         "WILSON'S PETREL": 259, 
         "WHITE-FACED STORM PETREL": 260, 
         "BLACK-BROWED ALBATROSS": 261, 
         "ATLANTIC YELLOW-NOSED ALBATROSS": 262, 
         "STORM PETREL": 263, 
         "SWINHOE'S PETREL": 264, 
         "LEACH'S PETREL": 265, 
         "FULMAR": 266, 
         "BLACK-CAPPED PETREL": 267, 
         "SCOPOLI'S SHEARWATER": 268, 
         "CORY'S SHEARWATER": 269, 
         "SOOTY SHEARWATER": 270, 
         "GREAT SHEARWATER": 271, 
         "MANX SHEARWATER": 272, 
         "YELKOUAN SHEARWATER": 273, 
         "BALEARIC SHEARWATER": 274, 
         "BAROLO SHEARWATER": 275, 
         "BLACK STORK": 276, 
         "WHITE STORK": 277, 
         "ASCENSION FRIGATEBIRD": 278, 
         "MAGNIFICENT FRIGATEBIRD": 279, 
         "GANNET": 280, 
         "RED-FOOTED BOOBY": 281, 
         "DOUBLE-CRESTED CORMORANT": 282, 
         "SHAG": 283, 
         "CORMORANT": 284, 
         "GLOSSY IBIS": 285, 
         "SPOONBILL": 286, 
         "BITTERN": 287, 
         "AMERICAN BITTERN": 288, 
         "LITTLE BITTERN": 289, 
         "NIGHT-HERON": 290, 
         "GREEN HERON": 291, 
         "SQUACCO HERON": 292, 
         "CHINESE POND HERON": 293, 
         "CATTLE EGRET": 294, 
         "GREY HERON": 295, 
         "GREAT BLUE HERON": 296, 
         "PURPLE HERON": 297, 
         "GREAT WHITE EGRET": 298, 
         "SNOWY EGRET": 299, 
         "LITTLE EGRET": 300, 
         "DALMATIAN PELICAN": 301, 
         "OSPREY": 302, 
         "EGYPTIAN VULTURE": 303, 
         "HONEY-BUZZARD": 304, 
         "SHORT-TOED EAGLE": 305, 
         "SPOTTED EAGLE": 306, 
         "GOLDEN EAGLE": 307, 
         "SPARROWHAWK": 308, 
         "GOSHAWK": 309, 
         "MARSH HARRIER": 310, 
         "HEN HARRIER": 311, 
         "NORTHERN HARRIER": 312, 
         "PALLID HARRIER": 313, 
         "MONTAGU'S HARRIER": 314, 
         "RED KITE": 315, 
         "BLACK KITE": 316, 
         "WHITE-TAILED EAGLE": 317, 
         "ROUGH-LEGGED BUZZARD": 318, 
         "BUZZARD": 319, 
         "BARN OWL": 320, 
         "SCOPS OWL": 321, 
         "SNOWY OWL": 322, 
         "TAWNY OWL": 323, 
         "HAWK OWL": 324, 
         "LITTLE OWL": 325, 
         "TENGMALM'S OWL": 326, 
         "LONG-EARED OWL": 327, 
         "SHORT-EARED OWL": 328, 
         "HOOPOE": 329, 
         "ROLLER": 330, 
         "KINGFISHER": 331, 
         "BELTED KINGFISHER": 332, 
         "BLUE-CHEEKED BEE-EATER": 333, 
         "BEE-EATER": 334, 
         "WRYNECK": 335, 
         "YELLOW-BELLIED SAPSUCKER": 336, 
         "LESSER SPOTTED WOODPECKER": 337, 
         "GREAT SPOTTED WOODPECKER": 338, 
         "GREEN WOODPECKER": 339, 
         "LESSER KESTREL": 340, 
         "KESTREL": 341, 
         "AMERICAN KESTREL": 342, 
         "RED-FOOTED FALCON": 343, 
         "AMUR FALCON": 344, 
         "ELEONORA'S FALCON": 345, 
         "MERLIN": 346, 
         "HOBBY": 347, 
         "GYR FALCON": 348, 
         "PEREGRINE": 349, 
         "RING-NECKED PARAKEET": 350, 
         "EASTERN PHOEBE": 351, 
         "ACADIAN FLYCATCHER": 352, 
         "ALDER FLYCATCHER": 353, 
         "EASTERN KINGBIRD": 354, 
         "BROWN SHRIKE": 355, 
         "RED-BACKED SHRIKE": 356, 
         "DAURIAN SHRIKE": 357, 
         "TURKESTAN SHRIKE": 358, 
         "LONG-TAILED SHRIKE": 359, 
         "LESSER GREY SHRIKE": 360, 
         "GREAT GREY SHRIKE": 361, 
         "WOODCHAT SHRIKE": 362, 
         "MASKED SHRIKE": 363, 
         "YELLOW-THROATED VIREO": 364, 
         "PHILADELPHIA VIREO": 365, 
         "RED-EYED VIREO": 366, 
         "GOLDEN ORIOLE": 367, 
         "JAY": 368, 
         "MAGPIE": 369, 
         "NUTCRACKER": 370, 
         "CHOUGH": 371, 
         "JACKDAW": 372, 
         "ROOK": 373, 
         "CARRION CROW": 374, 
         "HOODED CROW": 375, 
         "RAVEN": 376, 
         "WAXWING": 377, 
         "CEDAR WAXWING": 378, 
         "COAL TIT": 379, 
         "CRESTED TIT": 380, 
         "MARSH TIT": 381, 
         "WILLOW TIT": 382, 
         "BLUE TIT": 383, 
         "GREAT TIT": 384, 
         "PENDULINE TIT": 385, 
         "BEARDED TIT": 386, 
         "WOODLARK": 387, 
         "WHITE-WINGED LARK": 388, 
         "SKYLARK": 389, 
         "CRESTED LARK": 390, 
         "SHORE LARK": 391, 
         "SHORT-TOED LARK": 392, 
         "BIMACULATED LARK": 393, 
         "CALANDRA LARK": 394, 
         "BLACK LARK": 395, 
         "LESSER SHORT-TOED LARK": 396, 
         "SAND MARTIN": 397, 
         "TREE SWALLOW": 398, 
         "PURPLE MARTIN": 399, 
         "SWALLOW": 400, 
         "CRAG MARTIN": 401, 
         "HOUSE MARTIN": 402, 
         "RED-RUMPED SWALLOW": 403, 
         "AMERICAN CLIFF SWALLOW": 404, 
         "CETTI'S WARBLER": 405, 
         "LONG-TAILED TIT": 406, 
         "WOOD WARBLER": 407, 
         "WESTERN BONELLI'S WARBLER": 408, 
         "EASTERN BONELLI'S WARBLER": 409, 
         "HUME'S WARBLER": 410, 
         "YELLOW-BROWED WARBLER": 411, 
         "PALLAS'S WARBLER": 412, 
         "RADDE'S WARBLER": 413, 
         "DUSKY WARBLER": 414, 
         "WILLOW WARBLER": 415, 
         "CHIFFCHAFF": 416, 
         "IBERIAN CHIFFCHAFF": 417, 
         "EASTERN CROWNED WARBLER": 418, 
         "GREEN WARBLER": 419, 
         "TWO-BARRED GREENISH WARBLER": 420, 
         "GREENISH WARBLER": 421, 
         "PALE-LEGGED LEAF WARBLER": 422, 
         "ARCTIC WARBLER": 423, 
         "GREAT REED WARBLER": 424, 
         "AQUATIC WARBLER": 425, 
         "SEDGE WARBLER": 426, 
         "PADDYFIELD WARBLER": 427, 
         "BLYTH'S REED WARBLER": 428, 
         "REED WARBLER": 429, 
         "MARSH WARBLER": 430, 
         "THICK-BILLED WARBLER": 431, 
         "BOOTED WARBLER": 432, 
         "SYKES'S WARBLER": 433, 
         "EASTERN OLIVACEOUS WARBLER": 434, 
         "OLIVE-TREE WARBLER": 435, 
         "MELODIOUS WARBLER": 436, 
         "ICTERINE WARBLER": 437, 
         "PALLAS'S GRASSHOPPER WARBLER": 438, 
         "LANCEOLATED WARBLER": 439, 
         "GRASSHOPPER WARBLER": 440, 
         "RIVER WARBLER": 441, 
         "SAVI'S WARBLER": 442, 
         "FAN-TAILED WARBLER": 443, 
         "BLACKCAP": 444, 
         "GARDEN WARBLER": 445, 
         "BARRED WARBLER": 446, 
         "LESSER WHITETHROAT": 447, 
         "WESTERN ORPHEAN WARBLER": 448, 
         "EASTERN ORPHEAN WARBLER": 449, 
         "ASIAN DESERT WARBLER": 450, 
         "WHITETHROAT": 451, 
         "DARTFORD WARBLER": 452, 
         "MARMORA'S WARBLER": 453, 
         "SPECTACLED WARBLER": 454, 
         "SUBALPINE WARBLER": 455, 
         "MOLTONI'S SUBALPINE WARBLER": 456, 
         "SARDINIAN WARBLER": 457, 
         "RÜPPELL'S WARBLER": 458, 
         "FIRECREST": 459, 
         "GOLDCREST": 460, 
         "WREN": 461, 
         "NUTHATCH": 462, 
         "RED-BREASTED NUTHATCH": 463, 
         "WALLCREEPER": 464, 
         "TREECREEPER": 465, 
         "SHORT-TOED TREECREEPER": 466, 
         "GREY CATBIRD": 467, 
         "NORTHERN MOCKINGBIRD": 468, 
         "BROWN THRASHER": 469, 
         "ROSE-COLOURED STARLING": 470, 
         "STARLING": 471, 
         "SIBERIAN THRUSH": 472, 
         "WHITE'S THRUSH": 473, 
         "VARIED THRUSH": 474, 
         "VEERY": 475, 
         "GREY-CHEEKED THRUSH": 476, 
         "SWAINSON'S THRUSH": 477, 
         "HERMIT THRUSH": 478, 
         "WOOD THRUSH": 479, 
         "RING OUZEL": 480, 
         "BLACKBIRD": 481, 
         "EYEBROWED THRUSH": 482, 
         "BLACK-THROATED THRUSH": 483, 
         "RED-THROATED THRUSH": 484, 
         "NAUMANN'S THRUSH": 485, 
         "DUSKY THRUSH": 486, 
         "FIELDFARE": 487, 
         "REDWING": 488, 
         "SONG THRUSH": 489, 
         "MISTLE THRUSH": 490, 
         "AMERICAN ROBIN": 491, 
         "RUFOUS-TAILED SCRUB ROBIN": 492, 
         "SPOTTED FLYCATCHER": 493, 
         "ASIAN BROWN FLYCATCHER": 494, 
         "ROBIN": 495, 
         "SIBERIAN BLUE ROBIN": 496, 
         "RUFOUS-TAILED ROBIN": 497, 
         "BLUETHROAT": 498, 
         "THRUSH NIGHTINGALE": 499, 
         "NIGHTINGALE": 500, 
         "WHITE-THROATED ROBIN": 501, 
         "SIBERIAN RUBYTHROAT": 502, 
         "RED-FLANKED BLUETAIL": 503, 
         "PIED FLYCATCHER": 504, 
         "COLLARED FLYCATCHER": 505, 
         "RED-BREASTED FLYCATCHER": 506, 
         "TAIGA FLYCATCHER": 507, 
         "BLACK REDSTART": 508, 
         "REDSTART": 509, 
         "MOUSSIER'S REDSTART": 510, 
         "ROCK THRUSH": 511, 
         "BLUE ROCK THRUSH": 512, 
         "WHINCHAT": 513, 
         "STONECHAT": 514, 
         "SIBERIAN STONECHAT": 515, 
         "STEJNEGER'S STONECHAT": 516, 
         "WHEATEAR": 517, 
         "ISABELLINE WHEATEAR": 518, 
         "DESERT WHEATEAR": 519, 
         "WESTERN BLACK-EARED WHEATEAR": 520, 
         "EASTERN BLACK-EARED WHEATEAR": 521, 
         "PIED WHEATEAR": 522, 
         "WHITE-CROWNED BLACK WHEATEAR": 523, 
         "DIPPER": 524, 
         "HOUSE SPARROW": 525, 
         "SPANISH SPARROW": 526, 
         "TREE SPARROW": 527, 
         "ROCK SPARROW": 528, 
         "ALPINE ACCENTOR": 529, 
         "SIBERIAN ACCENTOR": 530, 
         "DUNNOCK": 531, 
         "YELLOW WAGTAIL": 532, 
         "EASTERN YELLOW WAGTAIL": 533, 
         "CITRINE WAGTAIL": 534, 
         "GREY WAGTAIL": 535, 
         "PIED WAGTAIL": 536, 
         "RICHARD'S PIPIT": 537, 
         "BLYTH'S PIPIT": 538, 
         "TAWNY PIPIT": 539, 
         "MEADOW PIPIT": 540, 
         "TREE PIPIT": 541, 
         "OLIVE-BACKED PIPIT": 542, 
         "PECHORA PIPIT": 543, 
         "RED-THROATED PIPIT": 544, 
         "BUFF-BELLIED PIPIT": 545, 
         "WATER PIPIT": 546, 
         "ROCK PIPIT": 547, 
         "CHAFFINCH": 548, 
         "BRAMBLING": 549, 
         "EVENING GROSBEAK": 550, 
         "HAWFINCH": 551, 
         "PINE GROSBEAK": 552, 
         "BULLFINCH": 553, 
         "TRUMPETER FINCH": 554, 
         "COMMON ROSEFINCH": 555, 
         "GREENFINCH": 556, 
         "TWITE": 557, 
         "LINNET": 558, 
         "COMMON REDPOLL": 559, 
         "LESSER REDPOLL": 560, 
         "ARCTIC REDPOLL": 561, 
         "PARROT CROSSBILL": 562, 
         "SCOTTISH CROSSBILL": 563, 
         "CROSSBILL": 564, 
         "TWO-BARRED CROSSBILL": 565, 
         "GOLDFINCH": 566, 
         "CITRIL FINCH": 567, 
         "SERIN": 568, 
         "SISKIN": 569, 
         "LAPLAND BUNTING": 570, 
         "SNOW BUNTING": 571, 
         "CORN BUNTING": 572, 
         "YELLOWHAMMER": 573, 
         "PINE BUNTING": 574, 
         "ROCK BUNTING": 575, 
         "ORTOLAN BUNTING": 576, 
         "CRETZSCHMAR'S BUNTING": 577, 
         "CIRL BUNTING": 578, 
         "CHESTNUT-EARED BUNTING": 579, 
         "LITTLE BUNTING": 580, 
         "YELLOW-BROWED BUNTING": 581, 
         "RUSTIC BUNTING": 582, 
         "YELLOW-BREASTED BUNTING": 583, 
         "CHESTNUT BUNTING": 584, 
         "BLACK-HEADED BUNTING": 585, 
         "BLACK-FACED BUNTING": 586, 
         "PALLAS'S REED BUNTING": 587, 
         "REED BUNTING": 588, 
         "SONG SPARROW": 589, 
         "WHITE-CROWNED SPARROW": 590, 
         "WHITE-THROATED SPARROW": 591, 
         "DARK-EYED JUNCO": 592, 
         "SAVANNAH SPARROW": 593, 
         "LARK SPARROW": 594, 
         "EASTERN TOWHEE": 595, 
         "BOBOLINK": 596, 
         "BALTIMORE ORIOLE": 597, 
         "RED-WINGED BLACKBIRD": 598, 
         "BROWN-HEADED COWBIRD": 599, 
         "OVENBIRD": 600, 
         "NORTHERN WATERTHRUSH": 601, 
         "GOLDEN-WINGED WARBLER": 602, 
         "BLACK-AND-WHITE WARBLER": 603, 
         "TENNESSEE WARBLER": 604, 
         "COMMON YELLOWTHROAT": 605, 
         "HOODED WARBLER": 606, 
         "AMERICAN REDSTART": 607, 
         "CAPE MAY WARBLER": 608, 
         "NORTHERN PARULA": 609, 
         "MAGNOLIA WARBLER": 610, 
         "BAY-BREASTED WARBLER": 611, 
         "BLACKBURNIAN WARBLER": 612, 
         "YELLOW WARBLER": 613, 
         "CHESTNUT-SIDED WARBLER": 614, 
         "BLACKPOLL WARBLER": 615, 
         "YELLOW-RUMPED WARBLER": 616, 
         "WILSON'S WARBLER": 617, 
         "SUMMER TANAGER": 618, 
         "SCARLET TANAGER": 619, 
         "ROSE-BREASTED GROSBEAK": 620, 
         "INDIGO BUNTING": 621
}