# renumbered x10 to allow space for insertions
birdlist = [
    "Capercaillie", 
    "Black Grouse", 
    "Ptarmigan", 
    "Red Grouse", 
    "Red-legged Partridge", 
    "Grey Partridge", 
    "Quail", 
    "Pheasant", 
    "Golden Pheasant", 
    "Lady Amherst's Pheasant", 
    "Brent Goose", 
    "Light-bellied Brent Goose",
    "Dark-bellied Brent Goose",
    "Red-breasted Goose", 
    "Canada Goose", 
    "Barnacle Goose", 
    "Cackling Goose", 
    "Snow Goose", 
    "Greylag Goose", 
    "Taiga Bean Goose", 
    "Pink-footed Goose", 
    "Tundra Bean Goose", 
    "White-fronted Goose", 
    "Lesser White-fronted Goose", 
    "Mute Swan", 
    "Bewick's Swan", 
    "Whooper Swan", 
    "Black Swan",
    "Egyptian Goose", 
    "Shelduck", 
    "RUDDY SHELDUCK", 
    "Mandarin Duck", 
    "Baikal Teal", 
    "Garganey", 
    "Blue-winged Teal", 
    "Shoveler", 
    "Gadwall", 
    "Falcated Duck", 
    "Wigeon", 
    "American Wigeon", 
    "Mallard", 
    "Black Duck", 
    "Pintail", 
    "Teal", 
    "Green-winged Teal", 
    "Red-crested Pochard", 
    "Canvasback", 
    "Redhead", 
    "Pochard", 
    "Ferruginous Duck", 
    "Ring-necked Duck", 
    "Tufted Duck", 
    "Scaup", 
    "LESSER SCAUP", 
    "Steller's Eider", 
    "King Eider", 
    "Eider", 
    "Harlequin Duck", 
    "Surf Scoter", 
    "Velvet Scoter", 
    "White-winged Scoter", 
    "Common Scoter", 
    "Black Scoter", 
    "Long-tailed Duck", 
    "Bufflehead", 
    "Goldeneye", 
    "Barrow's Goldeneye", 
    "Smew", 
    "Hooded Merganser", 
    "Goosander", 
    "Red-breasted Merganser", 
    "Ruddy Duck", 
    "Common Nighthawk", 
    "Red-necked Nightjar", 
    "Nightjar", 
    "Egyptian Nightjar", 
    "White-throated Needletail", 
    "Chimney Swift", 
    "Alpine Swift", 
    "Swift", 
    "PALLID SWIFT", 
    "Pacific Swift", 
    "Little Swift", 
    "White-rumped Swift", 
    "GREAT BUSTARD", 
    "Macqueen's Bustard", 
    "Little Bustard", 
    "Great Spotted Cuckoo", 
    "Yellow-billed Cuckoo", 
    "Black-billed Cuckoo", 
    "Cuckoo", 
    "Pallas's Sandgrouse", 
    "Rock Dove", 
    "Stock Dove", 
    "Woodpigeon", 
    "Turtle Dove", 
    "Oriental Turtle Dove", 
    "Collared Dove", 
    "Mourning Dove", 
    "Water Rail", 
    "Corncrake", 
    "Little Crake", 
    "Baillon's Crake", 
    "Spotted Crake", 
    "Sora Rail", 
    "Western Swamphen", 
    "Allen's Gallinule", 
    "American Purple Gallinule", 
    "Moorhen", 
    "Coot", 
    "American Coot", 
    "Sandhill Crane", 
    "Crane", 
    "Little Grebe", 
    "Pied-billed Grebe", 
    "Red-necked Grebe", 
    "Great Crested Grebe", 
    "Slavonian Grebe", 
    "Black-necked Grebe", 
    "Stone-curlew", 
    "Oystercatcher", 
    "Black-winged Stilt", 
    "Avocet", 
    "Lapwing", 
    "Sociable Plover", 
    "White-tailed Plover", 
    "Golden Plover", 
    "Pacific Golden Plover", 
    "American Golden Plover", 
    "Grey Plover", 
    "Ringed Plover", 
    "Semipalmated Plover", 
    "Little Ringed Plover", 
    "Killdeer", 
    "Kentish Plover", 
    "Lesser Sand Plover", 
    "Greater Sand Plover", 
    "Caspian Plover", 
    "Dotterel", 
    "Upland Sandpiper", 
    "Whimbrel", 
    "Hudsonian Whimbrel", 
    "Little Whimbrel", 
    "Eskimo Curlew", 
    "Curlew", 
    "Bar-tailed Godwit", 
    "Black-tailed Godwit", 
    "Hudsonian Godwit", 
    "Turnstone", 
    "Great Knot", 
    "Knot", 
    "Ruff", 
    "Broad-billed Sandpiper", 
    "Sharp-tailed Sandpiper", 
    "Stilt Sandpiper", 
    "Curlew Sandpiper", 
    "Temminck's Stint", 
    "Long-toed Stint", 
    "Red-necked Stint", 
    "Sanderling", 
    "Dunlin", 
    "Purple Sandpiper", 
    "Baird's Sandpiper", 
    "Little Stint", 
    "Least Sandpiper", 
    "White-rumped Sandpiper", 
    "Buff-breasted Sandpiper", 
    "Pectoral Sandpiper", 
    "SEMIPALMATED SANDPIPER", 
    "Western Sandpiper", 
    "Long-billed Dowitcher", 
    "Short-billed Dowitcher", 
    "Woodcock", 
    "Jack Snipe", 
    "Great Snipe", 
    "Snipe", 
    "Wilson's Snipe", 
    "Terek Sandpiper", 
    "Wilson's Phalarope", 
    "Red-necked Phalarope", 
    "Grey Phalarope", 
    "Common Sandpiper", 
    "Spotted Sandpiper", 
    "Green Sandpiper", 
    "Solitary Sandpiper", 
    "Grey-tailed Tattler", 
    "Lesser Yellowlegs", 
    "Redshank", 
    "Marsh Sandpiper", 
    "Wood Sandpiper", 
    "Spotted Redshank", 
    "Greenshank", 
    "Greater Yellowlegs", 
    "Cream-coloured Courser", 
    "Collared Pratincole", 
    "Oriental Pratincole", 
    "Black-winged Pratincole", 
    "Kittiwake", 
    "Ivory Gull", 
    "Sabine's Gull", 
    "Slender-billed Gull", 
    "Bonaparte's Gull", 
    "Black-headed Gull", 
    "Little Gull", 
    "Ross's Gull", 
    "Laughing Gull", 
    "Franklin's Gull", 
    "Audouin's Gull", 
    "Mediterranean Gull", 
    "Great Black-headed Gull", 
    "Common Gull", 
    "Ring-billed Gull", 
    "Great Black-backed Gull", 
    "Glaucous-winged Gull", 
    "Glaucous Gull", 
    "Iceland Gull", 
    "Herring Gull", 
    "American Herring Gull", 
    "Caspian Gull", 
    "Yellow-legged Gull", 
    "Slaty-backed Gull", 
    "Lesser Black-backed Gull", 
    "Gull-billed Tern", 
    "Caspian Tern", 
    "Royal Tern", 
    "Lesser Crested Tern", 
    "Sandwich Tern", 
    "Cabot's Tern", 
    "Elegant Tern", 
    "Little Tern", 
    "Least Tern", 
    "Aleutian Tern", 
    "Bridled Tern", 
    "Sooty Tern", 
    "Roseate Tern", 
    "Common Tern", 
    "Arctic Tern", 
    "Forster's Tern", 
    "Whiskered Tern", 
    "White-winged Black Tern", 
    "Black Tern", 
    "Great Skua", 
    "Pomarine Skua", 
    "Arctic Skua", 
    "Long-tailed Skua", 
    "Little Auk", 
    "Brünnich's Guillemot", 
    "Common Guillemot", 
    "Razorbill", 
    "Great Auk", 
    "BLACK GUILLEMOT", 
    "Long-billed Murrelet", 
    "Ancient Murrelet", 
    "Puffin", 
    "Tufted Puffin", 
    "Red-billed Tropicbird", 
    "Red-throated Diver", 
    "Black-throated Diver", 
    "Pacific Diver", 
    "Great Northern Diver", 
    "White-billed Diver", 
    "Wilson's Petrel", 
    "White-faced Storm Petrel", 
    "Black-browed Albatross", 
    "Atlantic Yellow-nosed Albatross", 
    "Storm Petrel", 
    "Swinhoe's Petrel", 
    "Leach's Petrel", 
    "Fulmar", 
    "Black-capped Petrel", 
    "Scopoli's Shearwater", 
    "Cory's Shearwater", 
    "Sooty Shearwater", 
    "Great Shearwater", 
    "Manx Shearwater", 
    "Yelkouan Shearwater", 
    "Balearic Shearwater", 
    "Barolo Shearwater", 
    "Black Stork", 
    "White Stork", 
    "Ascension Frigatebird", 
    "Magnificent Frigatebird", 
    "Gannet", 
    "Red-footed Booby", 
    "Double-crested Cormorant", 
    "Shag", 
    "Cormorant", 
    "Glossy Ibis", 
    "Spoonbill", 
    "Bittern", 
    "American Bittern", 
    "Little Bittern", 
    "Night-heron", 
    "Green Heron", 
    "Squacco Heron", 
    "Chinese Pond Heron", 
    "Cattle Egret", 
    "Grey Heron", 
    "Great Blue Heron", 
    "Purple Heron", 
    "Great White Egret", 
    "Snowy Egret", 
    "Little Egret", 
    "Dalmatian Pelican", 
    "Osprey", 
    "Egyptian Vulture", 
    "Honey-buzzard", 
    "Short-toed Eagle", 
    "Spotted Eagle", 
    "Golden Eagle", 
    "Sparrowhawk", 
    "Goshawk", 
    "Marsh Harrier", 
    "Hen Harrier", 
    "Northern Harrier", 
    "Pallid Harrier", 
    "Montagu's Harrier", 
    "Red Kite", 
    "Black Kite", 
    "WHITE-TAILED EAGLE", 
    "Rough-legged Buzzard", 
    "Buzzard", 
    "Barn Owl", 
    "Scops Owl", 
    "Snowy Owl", 
    "Tawny Owl", 
    "Hawk Owl", 
    "Little Owl", 
    "Tengmalm's Owl", 
    "Long-eared Owl", 
    "Short-eared Owl", 
    "Hoopoe", 
    "Roller", 
    "Kingfisher", 
    "Belted Kingfisher", 
    "Blue-cheeked Bee-eater", 
    "Bee-eater", 
    "Wryneck", 
    "Yellow-bellied Sapsucker", 
    "Lesser Spotted Woodpecker", 
    "Great Spotted Woodpecker", 
    "Green Woodpecker", 
    "Lesser Kestrel", 
    "Kestrel", 
    "American Kestrel", 
    "Red-footed Falcon", 
    "Amur Falcon", 
    "Eleonora's Falcon", 
    "Merlin", 
    "Hobby", 
    "Gyr Falcon", 
    "Peregrine", 
    "Ring-necked Parakeet", 
    "Eastern Phoebe", 
    "Acadian Flycatcher", 
    "Alder Flycatcher", 
    "Eastern Kingbird", 
    "Brown Shrike", 
    "Red-backed Shrike", 
    "Daurian Shrike", 
    "Turkestan Shrike", 
    "Long-tailed Shrike", 
    "Lesser Grey Shrike", 
    "Great Grey Shrike", 
    "Woodchat Shrike", 
    "Masked Shrike", 
    "Yellow-throated Vireo", 
    "Philadelphia Vireo", 
    "Red-eyed Vireo", 
    "Golden Oriole", 
    "Jay", 
    "Magpie", 
    "Nutcracker", 
    "CHOUGH", 
    "Jackdaw", 
    "Rook", 
    "Carrion Crow", 
    "Hooded Crow", 
    "Raven", 
    "Waxwing", 
    "Cedar Waxwing", 
    "Coal Tit", 
    "Crested Tit", 
    "Marsh Tit", 
    "Willow Tit", 
    "Blue Tit", 
    "Great Tit", 
    "Penduline Tit", 
    "Bearded Tit", 
    "Woodlark", 
    "White-winged Lark", 
    "Skylark", 
    "Crested Lark", 
    "Shore Lark", 
    "Short-toed Lark", 
    "Bimaculated Lark", 
    "Calandra Lark", 
    "Black Lark", 
    "Lesser Short-toed Lark", 
    "Sand Martin", 
    "Tree Swallow", 
    "Purple Martin", 
    "Swallow", 
    "Crag Martin", 
    "House Martin", 
    "Red-rumped Swallow", 
    "American Cliff Swallow", 
    "Cetti's Warbler", 
    "Long-tailed Tit", 
    "Wood Warbler", 
    "Western Bonelli's Warbler", 
    "Eastern Bonelli's Warbler", 
    "Hume's Warbler", 
    "Yellow-browed Warbler", 
    "Pallas's Warbler", 
    "Radde's Warbler", 
    "Dusky Warbler", 
    "Willow Warbler", 
    "Chiffchaff", 
    "Iberian Chiffchaff", 
    "Eastern Crowned Warbler", 
    "Green Warbler", 
    "Two-barred Greenish Warbler", 
    "Greenish Warbler", 
    "Pale-legged Leaf Warbler", 
    "Arctic Warbler", 
    "Great Reed Warbler", 
    "Aquatic Warbler", 
    "Sedge Warbler", 
    "Paddyfield Warbler", 
    "Blyth's Reed Warbler", 
    "Reed Warbler", 
    "Marsh Warbler", 
    "Thick-billed Warbler", 
    "Booted Warbler", 
    "Sykes's Warbler", 
    "EASTERN OLIVACEOUS WARBLER", 
    "Olive-tree Warbler", 
    "Melodious Warbler", 
    "Icterine Warbler", 
    "Pallas's Grasshopper Warbler", 
    "Lanceolated Warbler", 
    "Grasshopper Warbler", 
    "River Warbler", 
    "Savi's Warbler", 
    "Fan-tailed Warbler", 
    "Blackcap", 
    "Garden Warbler", 
    "Barred Warbler", 
    "Lesser Whitethroat", 
    "Western Orphean Warbler", 
    "Eastern Orphean Warbler", 
    "Asian Desert Warbler", 
    "Whitethroat", 
    "Dartford Warbler", 
    "Marmora's Warbler", 
    "Spectacled Warbler", 
    "SUBALPINE WARBLER", 
    "Moltoni's Subalpine Warbler", 
    "Sardinian Warbler", 
    "Rüppell's Warbler", 
    "Firecrest", 
    "Goldcrest", 
    "Wren", 
    "Nuthatch", 
    "Red-breasted Nuthatch", 
    "Wallcreeper", 
    "Treecreeper", 
    "Short-toed Treecreeper", 
    "Grey Catbird", 
    "Northern Mockingbird", 
    "Brown Thrasher", 
    "Rose-coloured Starling", 
    "Starling", 
    "Siberian Thrush", 
    "White's Thrush", 
    "Varied Thrush", 
    "Veery", 
    "Grey-cheeked Thrush", 
    "Swainson's Thrush", 
    "Hermit Thrush", 
    "Wood Thrush", 
    "Ring Ouzel", 
    "Blackbird", 
    "Eyebrowed Thrush", 
    "Black-throated Thrush", 
    "Red-throated Thrush", 
    "Naumann's Thrush", 
    "Dusky Thrush", 
    "Fieldfare", 
    "Redwing", 
    "Song Thrush", 
    "Mistle Thrush", 
    "American Robin", 
    "Rufous-tailed Scrub Robin", 
    "Spotted Flycatcher", 
    "Asian Brown Flycatcher", 
    "Robin", 
    "Siberian Blue Robin", 
    "Rufous-tailed Robin", 
    "Bluethroat", 
    "Thrush Nightingale", 
    "Nightingale", 
    "White-throated Robin", 
    "Siberian Rubythroat", 
    "Red-flanked Bluetail", 
    "Pied Flycatcher", 
    "Collared Flycatcher", 
    "Red-breasted Flycatcher", 
    "Taiga Flycatcher", 
    "Black Redstart", 
    "Redstart", 
    "Moussier's Redstart", 
    "Rock Thrush", 
    "Blue Rock Thrush", 
    "Whinchat", 
    "Stonechat", 
    "SIBERIAN STONECHAT", 
    "Stejneger's Stonechat", 
    "Wheatear", 
    "Isabelline Wheatear", 
    "Desert Wheatear", 
    "Western Black-eared Wheatear", 
    "Eastern Black-eared Wheatear", 
    "Pied Wheatear", 
    "White-crowned Black Wheatear", 
    "Dipper", 
    "House Sparrow", 
    "Spanish Sparrow", 
    "Tree Sparrow", 
    "Rock Sparrow", 
    "Alpine Accentor", 
    "Siberian Accentor", 
    "Dunnock", 
    "Yellow Wagtail", 
    "Eastern Yellow Wagtail", 
    "Citrine Wagtail", 
    "Grey Wagtail", 
    "Pied Wagtail", 
    "Richard's Pipit", 
    "Blyth's Pipit", 
    "Tawny Pipit", 
    "Meadow Pipit", 
    "Tree Pipit", 
    "Olive-backed Pipit", 
    "Pechora Pipit", 
    "Red-throated Pipit", 
    "Buff-bellied Pipit", 
    "Water Pipit", 
    "Rock Pipit", 
    "Chaffinch", 
    "Brambling", 
    "Evening Grosbeak", 
    "Hawfinch", 
    "Pine Grosbeak", 
    "Bullfinch", 
    "Trumpeter Finch", 
    "Common Rosefinch", 
    "Greenfinch", 
    "Twite", 
    "Linnet", 
    "Common Redpoll", 
    "Lesser Redpoll", 
    "Arctic Redpoll", 
    "Parrot Crossbill", 
    "Scottish Crossbill", 
    "Crossbill", 
    "Two-barred Crossbill", 
    "Goldfinch", 
    "Citril Finch", 
    "Serin", 
    "Siskin", 
    "Lapland Bunting", 
    "Snow Bunting", 
    "Corn Bunting", 
    "Yellowhammer", 
    "Pine Bunting", 
    "Rock Bunting", 
    "Ortolan Bunting", 
    "Cretzschmar's Bunting", 
    "Cirl Bunting", 
    "Chestnut-eared Bunting", 
    "Little Bunting", 
    "Yellow-browed Bunting", 
    "Rustic Bunting", 
    "Yellow-breasted Bunting", 
    "Chestnut Bunting", 
    "Black-headed Bunting", 
    "Black-faced Bunting", 
    "Pallas's Reed Bunting", 
    "Reed Bunting", 
    "Song Sparrow", 
    "White-crowned Sparrow", 
    "White-throated Sparrow", 
    "Dark-eyed Junco", 
    "Savannah Sparrow", 
    "Lark Sparrow", 
    "Eastern Towhee", 
    "Bobolink", 
    "Baltimore Oriole", 
    "Red-winged Blackbird", 
    "Brown-headed Cowbird", 
    "Ovenbird", 
    "Northern Waterthrush", 
    "Golden-winged Warbler", 
    "Black-and-white Warbler", 
    "Tennessee Warbler", 
    "Common Yellowthroat", 
    "Hooded Warbler", 
    "American Redstart", 
    "Cape May Warbler", 
    "Northern Parula", 
    "Magnolia Warbler", 
    "Bay-breasted Warbler", 
    "Blackburnian Warbler", 
    "Yellow Warbler", 
    "Chestnut-sided Warbler", 
    "Blackpoll Warbler", 
    "Yellow-rumped Warbler", 
    "Wilson's Warbler", 
    "Summer Tanager", 
    "Scarlet Tanager", 
    "Rose-breasted Grosbeak", 
    "Indigo Bunting"
]